
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Guilherme Del Fiol]|
|Lecturer(s)| |
|Content Author(s) | [Richard Bradshaw] |
|Content Contributor(s)|  |
|Content Editor(s)/Reviewer(s) | |
|Content Director(s) | |
|Content Consultants | |
|Acknowledgments| |
|**Production**||
|Content Publisher(s)| [Richard Bradshaw] |
|Content Publishing Reviewer(s)| |
|**Technical**||
|Course Publishing Engineer(s)| |
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen]|
|Package Developers ([ottrpal]) | [Candace Savonen], [John Muschelli], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)| [Richard Bradshaw] |
|Figure Artist(s)| [Richard Bradshaw] |
|Videographer(s)| |
|Videography Editor(s)| |
|Audiographer(s)| |
|Audiography Editor(s)| |
|**Funding**||
|Funder(s)| [NCI U24CA204800], [NCI U01CA232826] |
|Funding Staff| |

&nbsp;

<!-- Author information -->

[Guilherme Del Fiol]: https://https://medicine.utah.edu/faculty/mddetail/u0420797
[Richard Bradshaw]: https://scholar.google.com/citations?user=0lAuthAAAAAJ&hl=en
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!--Funding links -->
[NCI U24CA204800]: https://reporter.nih.gov/search/r6C7YNO7hkamZGNfiBrrFA/project-details/9979779
[NCI U01CA232826]: https://clinicaltrials.gov/ct2/show/NCT03985852

<!-- 
Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits
-->
